# Jekyll configuration

name: counter1nt3l
description: personal site to document things I'm interested in learning about

# Url is currently only used only for the RSS feed in feed.xml
url: http://counter1nt3l.github.io

author: counter1nt3l
copyright: 2018

share:
  email: true

social:
  rss: feed.xml

permalink: /:year/:month/:title

markdown: kramdown
kramdown:
  input: GFM # Enable GitHub Flavored Markdown (fenced code blocks)
  hard_wrap: true

exclude: ['README.md', 'LICENSE']
